#ifndef EVENTS_H
#define EVENTS_H

#define EVENT_MOUSE_BUTTON_RIGHT 1
#define EVENT_MOUSE_BUTTON_MIDDLE 1 << 1
#define EVENT_MOUSE_BUTTON_LEFT 1 << 2
#define EVENT_MOUSE_BUTTON_WHEEL_UP 1 << 3
#define EVENT_MOUSE_BUTTON_WHEEL_DOWN 1 << 4



#endif
